const state = {
  adminSecret: "",
  base: "",
};

function headers() {
  const h = { "Content-Type": "application/json" };
  if (state.adminSecret) h["x-admin-secret"] = state.adminSecret;
  return h;
}

async function login() {
  // Simple probe to validate admin access
  try {
    const res = await fetch("/admin/webhooks", { headers: headers() });
    if (!res.ok) throw new Error(await res.text());
    document.querySelector("#loginStatus").textContent = "OK";
    document.querySelector("#loginStatus").className = "status ok";
    await loadState();
  } catch (e) {
    document.querySelector("#loginStatus").textContent = "Errore";
    document.querySelector("#loginStatus").className = "status err";
  }
}

async function loadState() {
  const res = await fetch("/admin/ui/state", { headers: headers() });
  if (!res.ok) return;
  const data = await res.json();
  renderWebhooks(data.webhooks || []);
  renderEmails(data.emailTriggers || []);
}

function renderWebhooks(items) {
  const tbody = document.querySelector("#webhooksTable tbody");
  tbody.innerHTML = "";
  for (const w of items) {
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td>${escapeHtml(w.name)}</td>
      <td><code>${escapeHtml(w.path)}</code></td>
      <td><code>${escapeHtml(w.url)}</code></td>
      <td>${w.permanentToken ? `<code>${escapeHtml(w.permanentToken)}</code>` : '<em>nascosto</em>'}</td>
      <td>
        <button class="action secondary" data-action="info" data-name="${escapeAttr(w.name)}">Info</button>
        <button class="action" data-action="ephemeral" data-name="${escapeAttr(w.name)}">Genera URL temporaneo</button>
        <button class="action warn" data-action="regenerate" data-name="${escapeAttr(w.name)}">Rigenera token</button>
      </td>
    `;
    tbody.appendChild(tr);
  }
}

function renderEmails(items) {
  const tbody = document.querySelector("#emailTable tbody");
  tbody.innerHTML = "";
  for (const e of items) {
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td>${escapeHtml(e.name)}</td>
      <td>${escapeHtml(e.imapHost || "")}</td>
      <td>${e.debounceSeconds ?? 0}</td>
      <td>${e.durationSeconds ?? 10}</td>
    `;
    tbody.appendChild(tr);
  }
}

async function onTableClick(ev) {
  const btn = ev.target.closest("button[data-action]");
  if (!btn) return;
  const name = btn.getAttribute("data-name");
  const action = btn.getAttribute("data-action");
  try {
    if (action === "info") {
      const res = await fetch(`/admin/webhooks/${encodeURIComponent(name)}/info`, { headers: headers() });
      const data = await res.json();
      showEphemeral(`URL: ${escapeHtml(data.url)}\nPath: ${escapeHtml(data.path)}\nAutogenerated: ${data.tokenAutogenerated}`);
    } else if (action === "ephemeral") {
      const ttl = 300;
      const res = await fetch(`/admin/webhooks/${encodeURIComponent(name)}/ephemeral?ttl=${ttl}`, { method: "POST", headers: headers() });
      const data = await res.json();
      showEphemeral(`URL temporaneo (TTL ${data.ttlSeconds}s):\n${escapeHtml(data.url)}`);
    } else if (action === "regenerate") {
      if (!confirm(`Rigenerare il token permanente per '${name}'?`)) return;
      const res = await fetch(`/admin/webhooks/${encodeURIComponent(name)}/regenerate`, { method: "POST", headers: headers() });
      const data = await res.json();
      showEphemeral(`Nuovo token permanente (prima rivelazione):\n${escapeHtml(data.url)}`);
      await loadState();
    }
  } catch (e) {
    alert("Errore: " + (e?.message || e));
  }
}

function showEphemeral(text) {
  const sec = document.querySelector("#ephemeralOutput");
  const div = document.querySelector("#ephemeralContent");
  div.textContent = text;
  sec.classList.remove("hidden");
}

function escapeHtml(s) { return String(s).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])); }
function escapeAttr(s) { return escapeHtml(s).replace(/"/g, '&quot;'); }

// Wire events
window.addEventListener("DOMContentLoaded", () => {
  document.querySelector("#btnLogin").addEventListener("click", () => {
    state.adminSecret = document.querySelector("#adminSecret").value.trim();
    login();
  });
  document.querySelector("#webhooksTable").addEventListener("click", onTableClick);
});
