"use strict";

const { v4: uuidv4 } = require("uuid");

module.exports = function setupWebhooks(platform) {
	for (const wh of platform.webhooks) {
		const key = `webhook:${wh.name}`;
		const accessory = platform._getOrCreateAccessory(key, wh.name);

		// Keep runtime control values
		wh._duration = Math.max(0, (wh.durationSeconds || 10)) * 1000;
		wh._debounce = Math.max(0, (wh.debounceSeconds || 0)) * 1000;
		wh._lastTrigger = 0;
		wh._id = accessory.UUID;

		// Prepare token: if not specified, use stored or generate
		const ctx = accessory.context || {};
		if (!wh.token) {
			if (ctx.token) {
				wh.token = ctx.token;
				wh._autogenerated = !!ctx.tokenAutogenerated;
			} else {
				wh.token = uuidv4();
				wh._autogenerated = true;
				ctx.token = wh.token;
				ctx.tokenAutogenerated = true;
				ctx.tokenRevealed = false;
				accessory.context = ctx;
				platform.api.updatePlatformAccessories([accessory]);
				// Intenzionalmente non logghiamo il token; l'utente può recuperarlo via endpoint admin.
			}
		}

		// Compute path
		const fullPath = platform._computeWebhookPath(wh);

		// Prepare optional allowlist
		const allowList = (wh.allowedIps || "")
			.split(",")
			.map((s) => s.trim())
			.filter(Boolean);

		const handler = async (req, res) => {
			const ip = platform._getRemoteIp(req);
			if (allowList.length > 0 && !allowList.includes(ip)) {
				platform.log.warn(`Webhook '${wh.name}' blocked by allowlist: ${ip}`);
				return res.status(403).json({ error: "forbidden" });
			}

			// Token header or query
			const token = req.get("x-webhook-token") || req.query.token || req.body?.token;
			if (!token || token !== wh.token) {
				platform.log.warn(`Webhook '${wh.name}': invalid or missing token from ${ip}`);
				return res.status(401).json({ error: "unauthorized" });
			}

			// Debounce/cooldown
			const now = Date.now();
			if (wh._debounce > 0 && now - wh._lastTrigger < wh._debounce) {
				platform.log.debug(`Webhook '${wh.name}' ignored by debounce (${now - wh._lastTrigger}ms < ${wh._debounce}ms)`);
				return res.json({ ok: true, debounced: true });
			}
			wh._lastTrigger = now;

			platform._triggerAccessory(wh.name, accessory, wh._duration);
			platform.log.info(`Webhook '${wh.name}' fired by ${ip}`);
			return res.json({ ok: true });
		};

		// Register both GET and POST
		platform.app.get(fullPath, handler);
		platform.app.post(fullPath, handler);

		platform.log.info(`Webhook '${wh.name}' ready at ${platform._serverBaseUrl()}${fullPath} (token via header x-webhook-token or ?token=...)`);
	}
}
